# Data Analytics Visualization Experiment 1
---

**RIA KHETANI**

**D11AD_34**

**AIM:** Getting introduced to data analytics libraries in Python and R.

**OBJECTIVE:** Explore various data analytics Libraries in R and Python.



# Tasks to be performed :

---

1. Explore Top-5 Data Analytics Libraries in Python (w.r.t Features & Applications).

2. Explore Top-5 Data Analytics Libraries in R (w.r.t Features & Applications)

3. Install 2 Libraries each for Python and R.

4. Perform simple experiments on the 2 identified libraries each for Python and R

5. Prepare a document with the Aim, Tasks performed, Program, Output, and Conclusion.






**1.Explore Top-5 Data Analytics Libraries in Python (w.r.t Features & Applications)**

---



**1.NumPy**


NumPy is the fundamental package for scientific computing in Python. It
is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.


**2. Pandas**


Pandas is a Python library used for working with data sets. It has functions for analyzing, cleaning, exploring, and manipulating data.The name "Pandas" has a reference to both "Panel Data", and "Python Data Analysis" and was created by Wes McKinney in 2008.


**3. Scikit-learn**


Scikit-learn (Sklearn) is the most useful and robust library for machine learning in Python. It provides a selection of efficient tools for machine learning and statistical modeling including classification, regression, clustering and dimensionality reduction via a consistence interface in Python. This library, which is largely written in Python, is built upon NumPy, SciPy and Matplotlib.


**4. SciPy**


The SciPy is an open-source scientific library of Python that is distributed under a BSD license. It is used to solve the complex scientific and mathematical problems. It is built on top of the Numpy extension, which means if we import the SciPy, there is no need to import Numpy. The SciPy library supports integration, gradient optimization, special functions, ordinary differential equation solvers, parallel programming tools, and many more.

**5. Tensorflow**

TensorFlow is an open-source machine learning library developed by Google. TensorFlow is used to build and train deep learning models as it facilitates the creation of computational graphs and efficient execution on various hardware platforms.TensorFlow is basically a software library for numerical computation using data flow graphs where:
nodes in the graph represent mathematical operations.
edges in the graph represent the multidimensional data arrays (called tensors) communicated between them.

**Install any 2 libraries in Python**

---

**python**:

In [ ]:
!pip install pandas

In [ ]:
!pip install numpy

**Performing experiments**

---

In [ ]:
import pandas as pd


# reading the database
data = pd.read_csv("tips.csv")

# printing the top 10 rows
display(data.head(10))


total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4
5       25.29  4.71    Male     No  Sun  Dinner     4
6        8.77  2.00    Male     No  Sun  Dinner     2
7       26.88  3.12    Male     No  Sun  Dinner     4
8       15.04  1.96    Male     No  Sun  Dinner     2
9       14.78  3.23    Male     No  Sun  Dinner     2

In [ ]:
# Python program for
# Creation of Arrays
import numpy as np

# Creating a rank 1 Array
arr = np.array([1, 2, 3])
print("Array with Rank 1: \n",arr)

# Creating a rank 2 Array
arr = np.array([[1, 2, 3],
                [4, 5, 6]])
print("Array with Rank 2: \n", arr)

# Creating an array from tuple
arr = np.array((1, 3, 2))
print("\nArray created using "
      "passed tuple:\n", arr)

Array with Rank 1: 
 [1 2 3]
Array with Rank 2: 
 [[1 2 3]
 [4 5 6]]

Array created using passed tuple:
 [1 3 2]


**Explore Top-5 Data Analytics Libraries in R (w.r.t Features & Applications)**

---

**1. dplyr**

The dplyr is a powerful R-package to manipulate, clean and summarize unstructured data. In short, it makes data exploration and data manipulation easy and fast in R.The package "dplyr" comprises many functions that perform mostly used data manipulation operations such as applying filter, selecting specific columns, sorting data, adding or deleting columns and aggregating data. Another most important advantage of this package is that it's very easy to learn and use dplyr functions.

**2. stringr**

The stringr package provides a cohesive set of functions designed to make working with strings as easy as possible. stringr is built on top of stringi, which uses the ICU C library to provide fast, correct implementations of common string manipulations. stringr focusses on the most important and commonly used string manipulation functions whereas stringi provides a comprehensive set covering almost anything and everything.

**3. readr**

The readr package in R, part of the tidyverse, is designed to simplify and streamline the process of reading and importing structured text data. Its philosophy centers around consistency, simplicity, and efficiency. By adhering to these principles, readr aims to provide a user-friendly experience for handling data.One of the key features is the consistent and straightforward interface across its functions. This uniformity makes it easier for users to remember and apply the various functions within the package.

**4. ggplot2**

ggplot2 in R is a versatile data visualization package that operates on the grammar of graphics principles. Developed by Hadley Wickham, it simplifies the creation of complex visualizations by breaking down graphics into fundamental components. The layered approach allows users to build up plots by adding components incrementally. Aesthetic mappings play a crucial role, defining how variables are represented visually. For instance, one can map data variables to plot aesthetics such as color, size, or shape. With a rich set of geoms (geometric objects) and statistical transformations, ggplot2 facilitates the creation of diverse and informative visualizations. Its theming system provides flexibility for customization, enabling users to adapt the appearance of plots to their specific needs.

**5. tseries**

The lubridate package in R is a powerful and user-friendly library for handling date and time data. It simplifies the often complex and error-prone process of working with dates by providing intuitive functions that facilitate parsing, manipulation, and formatting of date-time objects. Developed by Hadley Wickham, lubridate builds on R's base date and time functions, offering a consistent and convenient interface for tasks such as extracting components (e.g., year, month, day), arithmetic operations, and handling time zones. One of its key features is the ability to handle both date and time information seamlessly, making it well-suited for various data analysis and visualization tasks where accurate temporal information is crucial. The package has gained popularity in the R community for its simplicity, versatility, and efficiency in handling temporal data, making it an essential tool for users working with time series, financial data, and other applications involving dates and times.

**Installing any two packages from R**:

---

In [ ]:
install.packages("dplyr")

In [ ]:
install.packages("tidyverse")

**Performing Experiments**

---

In [ ]:
library(dplyr)


In [ ]:
library(readr)


In [ ]:
mydata = read.csv("sampledata.csv")


In [ ]:
sample_n(mydata,3)


Index State      Y2002   Y2003   Y2004   Y2005   Y2006   Y2007   Y2008  
1 I     Idaho      1353210 1438538 1739154 1541015 1122387 1772050 1335481
2 C     California 1685349 1675807 1889570 1480280 1735069 1812546 1487315
3 M     Missouri   1221316 1858368 1773451 1573967 1374863 1486197 1735099
  Y2009   Y2010   Y2011   Y2012   Y2013   Y2014   Y2015  
1 1748608 1436809 1456340 1643855 1312561 1713718 1757171
2 1663809 1624509 1639670 1921845 1156536 1388461 1644607
3 1800620 1164202 1425363 1800052 1698105 1767835 1996005

In [ ]:
mydata7 = filter(mydata, Index == "A")
print(mydata7)

  Index    State   Y2002   Y2003   Y2004   Y2005   Y2006   Y2007   Y2008
1     A  Alabama 1296530 1317711 1118631 1492583 1107408 1440134 1945229
2     A   Alaska 1170302 1960378 1818085 1447852 1861639 1465841 1551826
3     A  Arizona 1742027 1968140 1377583 1782199 1102568 1109382 1752886
4     A Arkansas 1485531 1994927 1119299 1947979 1669191 1801213 1188104
    Y2009   Y2010   Y2011   Y2012   Y2013   Y2014   Y2015
1 1944173 1237582 1440756 1186741 1852841 1558906 1916661
2 1436541 1629616 1230866 1512804 1985302 1580394 1979143
3 1554330 1300521 1130709 1907284 1363279 1525866 1647724
4 1628980 1669295 1928238 1216675 1591896 1360959 1329341


In [ ]:
mydata1 = read.csv("sampledata.csv")
print(mydata1)

   Index                State   Y2002   Y2003   Y2004   Y2005   Y2006   Y2007
1      A              Alabama 1296530 1317711 1118631 1492583 1107408 1440134
2      A               Alaska 1170302 1960378 1818085 1447852 1861639 1465841
3      A              Arizona 1742027 1968140 1377583 1782199 1102568 1109382
4      A             Arkansas 1485531 1994927 1119299 1947979 1669191 1801213
5      C           California 1685349 1675807 1889570 1480280 1735069 1812546
6      C             Colorado 1343824 1878473 1886149 1236697 1871471 1814218
7      C          Connecticut 1610512 1232844 1181949 1518933 1841266 1976976
8      D             Delaware 1330403 1268673 1706751 1403759 1441351 1300836
9      D District of Columbia 1111437 1993741 1374643 1827949 1803852 1595981
10     F              Florida 1964626 1468852 1419738 1362787 1339608 1278550
11     G              Georgia 1929009 1541565 1810773 1779091 1326846 1223770
12     H               Hawaii 1461570 1200280 1213993 1245931 14

In [ ]:
read_delim("sampledata.csv",  skip = 45)

Rows: 6 Columns: 16
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr  (2): U, Utah
dbl (14): 1771096, 1195861, 1979395, 1241662, 1437456, 1859416, 1939284, 191...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.


U Utah          1771096 1195861 1979395 1241662 1437456 1859416 1939284
1 V Vermont       1146902 1832249 1492704 1579265 1332048 1563537 1123567
2 V Virginia      1134317 1163996 1891068 1853855 1708715 1197698 1803330
3 W Washington    1977749 1687136 1199490 1163092 1334864 1621989 1545621
4 W West Virginia 1677347 1380662 1176100 1888948 1922085 1740826 1238174
5 W Wisconsin     1788920 1518578 1289663 1436888 1251678 1721874 1980167
6 W Wyoming       1775190 1498098 1198212 1881688 1750527 1523124 1587602
  1915865 1619186 1288285 1108281 1123353 1801019 1729273
1 1618583 1326369 1792600 1714960 1146278 1282790 1565924
2 1590043 1516758 1171686 1262342 1647032 1706707 1850394
3 1555554 1179331 1150089 1775787 1273834 1387428 1377341
4 1539322 1539603 1872519 1462137 1683127 1204344 1198791
5 1901394 1648755 1940943 1729177 1510119 1701650 1846238
6 1504455 1282142 1881814 1673668 1994022 1204029 1853858